# Generated by Django 2.0.6 on 2018-06-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('time', models.TimeField(db_index=True, verbose_name='time')),
                ('source_ip', models.GenericIPAddressField(db_index=True, default=None, null=True, verbose_name='source ip')),
                ('url', models.URLField(db_index=True, max_length=256, verbose_name='url')),
                ('username', models.CharField(db_index=True, max_length=48, verbose_name='username')),
                ('password', models.CharField(db_index=True, max_length=48, verbose_name='password')),
                ('params', models.TextField(verbose_name='parameters')),
            ],
        ),
    ]
