# Generated by Django 2.0.6 on 2018-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFileEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(db_index=True, max_length=32, verbose_name='logfile id')),
                ('date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('user', models.CharField(db_index=True, max_length=32, verbose_name='user')),
                ('task', models.CharField(db_index=True, max_length=64, verbose_name='task')),
                ('text', models.TextField(db_index=True, verbose_name='text')),
            ],
        ),
    ]
