# Generated by Django 2.0.6 on 2018-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0002_auto_20180620_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfileentry',
            name='source_ip',
            field=models.GenericIPAddressField(db_index=True, default=None, null=True, verbose_name='source ip'),
        ),
    ]
