# Generated by Django 2.0.6 on 2018-06-25 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0003_logfileentry_source_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', editable=False, max_length=100, verbose_name='name')),
                ('count', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='count')),
                ('date_started', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='started')),
                ('date_finished', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='finished')),
                ('duration', models.DurationField(blank=True, db_index=True, default=None, null=True, verbose_name='duration')),
                ('log_text', models.TextField(blank=True, default=None, null=True, verbose_name='log')),
                ('error_text', models.TextField(blank=True, default=None, null=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'Worker Log',
                'verbose_name_plural': 'Worker Logs',
            },
        ),
        migrations.CreateModel(
            name='NslookupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('response', models.TextField(blank=True, default=None, null=True, verbose_name='response')),
            ],
            options={
                'verbose_name': 'Nslookup Requests',
                'verbose_name_plural': 'Nslookup Requests',
            },
        ),
        migrations.CreateModel(
            name='WhoisRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('response', models.TextField(blank=True, default=None, null=True, verbose_name='response')),
            ],
            options={
                'verbose_name': 'Whois Requests',
                'verbose_name_plural': 'Whois Requests',
            },
        ),
    ]
